CREATE SCHEMA IF NOT EXISTS `Tier` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
use Tier;

CREATE TABLE IF NOT EXISTS AC_SUBSCRIPTION_PLANS (
    PLAN_ID	INTEGER NOT NULL AUTO_INCREMENT,
    PLAN_NAME   VARCHAR(200) NOT NULL,	
    MAX_APPLICATIONS	INT NOT NULL,
    PRIMARY KEY (PLAN_ID)
);

CREATE TABLE IF NOT EXISTS AC_CONTAINER_SPECIFICATIONS (
    CON_SPEC_ID     INTEGER NOT NULL AUTO_INCREMENT,
    CON_SPEC_NAME   VARCHAR(200) NOT NULL,
    CPU              INT NOT NULL,	
    MEMORY	     INT NOT NULL,
    STORAGE	     INT NOT NULL,
    COST_PER_HOUR    INT NOT NULL,
    PRIMARY KEY (CON_SPEC_ID)
);

CREATE TABLE IF NOT EXISTS Subscription (
    PLAN_ID         INTEGER NOT NULL,
    APP_OWNER_ID    INTEGER NOT NULL,
    START_DATE	    DATE NOT NULL,	
    STATUS          boolean NOT NULL,
    PRIMARY KEY (APP_OWNER_ID),
    FOREIGN KEY (PLAN_ID) REFERENCES Plan(PLAN_ID)
);

CREATE TABLE IF NOT EXISTS RestrictedPlanContainerSpecs (
    PLAN_ID           INTEGER NOT NULL,
    CON_SPEC_ID       INTEGER NOT NULL,
    PRIMARY KEY (PLAN_ID,CON_SPEC_ID),
    FOREIGN KEY (PLAN_ID) REFERENCES Plan (PLAN_ID),
    FOREIGN KEY (CON_SPEC_ID) REFERENCES ContainerSpecs(CON_SPEC_ID)
);

CREATE TABLE IF NOT EXISTS OrganizationContainerSpecsInformation (
    ID          	INTEGER NOT NULL AUTO_INCREMENT,
    CON_SPEC_ID        	INTEGER(200),  
    APP_OWNER_ID	INTEGER (200),
    PLAN_ID             INTEGER (200) NOT NULL, 
    PRIMARY KEY (ID),
    FOREIGN KEY (CON_SPEC_ID) REFERENCES ContainerSpecs(CON_SPEC_ID),
    FOREIGN KEY (APP_OWNER_ID) REFERENCES Subscription(APP_OWNER_ID)
);

INSERT INTO Plan (PLAN_NAME ,TEAM , MAX_INSTANCES , MAX_LC) VALUES ("FREE",10,6,3);
INSERT INTO Plan (PLAN_NAME ,TEAM , MAX_INSTANCES , MAX_LC) VALUES ("PAID_SMALL",20,30,10);
INSERT INTO Plan (PLAN_NAME ,TEAM , MAX_INSTANCES , MAX_LC) VALUES ("PAID_MEDIUM",100,100,20);

INSERT INTO ContainerSpecs (CON_SPEC_NAME , CPU , MEMORY , STORAGE , COST_PER_HOUR) VALUES ("t2.small",1,2,4,1);
INSERT INTO ContainerSpecs (CON_SPEC_NAME , CPU , MEMORY , STORAGE , COST_PER_HOUR) VALUES ("t2.medium",2,4,8,2);
INSERT INTO ContainerSpecs (CON_SPEC_NAME , CPU , MEMORY , STORAGE , COST_PER_HOUR) VALUES ("t2.large",4,8,16,4);
INSERT INTO ContainerSpecs (CON_SPEC_NAME , CPU , MEMORY , STORAGE , COST_PER_HOUR) VALUES ("m2.small",2,2,4,2);
INSERT INTO ContainerSpecs (CON_SPEC_NAME , CPU , MEMORY , STORAGE , COST_PER_HOUR) VALUES ("m2.medium",3,4,8,4);
INSERT INTO ContainerSpecs (CON_SPEC_NAME , CPU , MEMORY , STORAGE , COST_PER_HOUR) VALUES ("m2.large",4,8,16,6);

INSERT INTO Subscription (PLAN_ID ,APP_OWNER_ID, START_DATE, STATUS ) VALUES ("1","00001","2012-04-18",true);
INSERT INTO Subscription (PLAN_ID ,APP_OWNER_ID, START_DATE, STATUS ) VALUES ("2","00002","2012-04-18",true);
INSERT INTO Subscription (PLAN_ID ,APP_OWNER_ID, START_DATE, STATUS ) VALUES ("1","00003","2012-04-18",true);
INSERT INTO Subscription (PLAN_ID ,APP_OWNER_ID, START_DATE, STATUS ) VALUES ("2","00004","2012-04-18",true);
INSERT INTO Subscription (PLAN_ID ,APP_OWNER_ID, START_DATE, STATUS ) VALUES ("1","00005","2012-04-18",true);
INSERT INTO Subscription (PLAN_ID ,APP_OWNER_ID, START_DATE, STATUS ) VALUES ("1","00006","2012-04-18",true);
INSERT INTO Subscription (PLAN_ID ,APP_OWNER_ID, START_DATE, STATUS ) VALUES ("3","00007","2012-04-18",true);

INSERT INTO RestrictedPlanContainerSpecs(PLAN_ID, CON_SPEC_ID) VALUES ("1","1");
INSERT INTO RestrictedPlanContainerSpecs(PLAN_ID, CON_SPEC_ID) VALUES ("1","2");
INSERT INTO RestrictedPlanContainerSpecs(PLAN_ID, CON_SPEC_ID) VALUES ("1","4");

INSERT INTO OrganizationContainerSpecsInformation ( CON_SPEC_ID , APP_OWNER_ID , PLAN_ID) VALUES (1,1,1);
INSERT INTO OrganizationContainerSpecsInformation ( CON_SPEC_ID , APP_OWNER_ID , PLAN_ID) VALUES (2,2,1);
INSERT INTO OrganizationContainerSpecsInformation ( CON_SPEC_ID , APP_OWNER_ID , PLAN_ID) VALUES (1,4,2);
INSERT INTO OrganizationContainerSpecsInformation ( CON_SPEC_ID , APP_OWNER_ID , PLAN_ID) VALUES (5,3,2);
INSERT INTO OrganizationContainerSpecsInformation ( CON_SPEC_ID , APP_OWNER_ID , PLAN_ID) VALUES (2,4,2);
INSERT INTO OrganizationContainerSpecsInformation ( CON_SPEC_ID , APP_OWNER_ID , PLAN_ID) VALUES (4,3,2);


